"""Pydantic models for fitness tracking."""

from enum import Enum

from pydantic import BaseModel, Field


class MealType(str, Enum):
    """Type of meal for calorie tracking."""

    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"
    SNACK = "snack"


class ExerciseType(str, Enum):
    """Type of exercise for workout tracking."""

    STRENGTH = "strength"
    CARDIO = "cardio"
    FLEXIBILITY = "flexibility"
    SPORTS = "sports"
    OTHER = "other"


class CalorieEntry(BaseModel):
    """A calorie/food entry for tracking nutrition.

    Attributes:
        id: Unique identifier (auto-generated by the database).
        user_id: ID of the user who logged this entry.
        date: Date of the entry (YYYY-MM-DD format).
        food_item: Description of the food consumed.
        calories: Number of calories.
        protein: Grams of protein (optional).
        carbs: Grams of carbohydrates (optional).
        fat: Grams of fat (optional).
        meal_type: Type of meal (breakfast, lunch, dinner, snack).
        notes: Additional notes (optional).
        created_at: When the entry was created (ISO format string).
    """

    id: int | None = None
    user_id: str
    date: str  # YYYY-MM-DD format
    food_item: str
    calories: int = Field(ge=0)
    protein: float | None = Field(default=None, ge=0)
    carbs: float | None = Field(default=None, ge=0)
    fat: float | None = Field(default=None, ge=0)
    meal_type: MealType = MealType.SNACK
    notes: str | None = None
    created_at: str  # ISO format datetime string


class WorkoutEntry(BaseModel):
    """A workout/exercise entry for tracking fitness activities.

    Attributes:
        id: Unique identifier (auto-generated by the database).
        user_id: ID of the user who logged this entry.
        date: Date of the workout (YYYY-MM-DD format).
        exercise_type: Type of exercise (strength, cardio, etc.).
        exercise_name: Name of the exercise performed.
        duration_minutes: Duration in minutes (optional).
        set: Sequence number for the logged set (for strength training).
        reps: Number of reps per set (for strength training).
        weight: Weight used in kg (for strength training).
        distance_km: Distance in kilometers (for cardio).
        notes: Additional notes (optional).
        created_at: When the entry was created (ISO format string).
    """

    id: int | None = None
    user_id: str
    date: str  # YYYY-MM-DD format
    exercise_type: ExerciseType = ExerciseType.OTHER
    exercise_name: str
    duration_minutes: int | None = Field(default=None, ge=0)
    set: int | None = Field(default=None, ge=1)
    reps: int | None = Field(default=None, ge=0)
    weight: float | None = Field(default=None, ge=0)
    distance_km: float | None = Field(default=None, ge=0)
    notes: str | None = None
    created_at: str  # ISO format datetime string
