"""SQLite-based storage for scheduled reminders.

This module provides persistent storage for reminders that can survive
bot restarts. Each reminder stores the user's Telegram chat ID for
push notifications.
"""

import asyncio
import logging
import sqlite3
from datetime import UTC, datetime
from pathlib import Path

from pydantic import BaseModel

from ..utils.config import get_data_dir

logger = logging.getLogger(__name__)


def _get_default_db_path() -> Path:
    """Get the default database path in the agent data directory."""
    return get_data_dir() / "reminders.db"


class Reminder(BaseModel):
    """A scheduled reminder.

    Attributes:
        id: Unique identifier (auto-generated by SQLite).
        user_id: Telegram chat ID of the user who set the reminder.
        message: The reminder message to send.
        trigger_time: When to send the reminder (ISO format string).
        is_sent: Whether the reminder has been sent.
        created_at: When the reminder was created (ISO format string).
    """

    id: int | None = None
    user_id: str
    message: str
    trigger_time: str  # ISO format datetime string
    is_sent: bool = False
    created_at: str  # ISO format datetime string


class ReminderStorage:
    """SQLite-based storage for reminders.

    This class provides CRUD operations for reminders with proper
    async handling using a dedicated thread.

    Attributes:
        db_path: Path to the SQLite database file.
    """

    def __init__(self, db_path: Path | None = None) -> None:
        """Initialize the reminder storage.

        Args:
            db_path: Optional path to SQLite database file.
                Defaults to <agent_data_dir>/reminders.db
        """
        self.db_path = db_path or _get_default_db_path()
        self._lock = asyncio.Lock()
        self._initialized = False

    def _ensure_db_dir(self) -> None:
        """Ensure the database directory exists."""
        self.db_path.parent.mkdir(parents=True, exist_ok=True)

    def _get_connection(self) -> sqlite3.Connection:
        """Get a database connection with proper configuration.

        Returns:
            A configured SQLite connection.
        """
        conn = sqlite3.connect(self.db_path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        return conn

    async def initialize(self) -> None:
        """Initialize the database schema.

        Creates the reminders table if it doesn't exist.
        """
        async with self._lock:
            if self._initialized:
                return

            self._ensure_db_dir()
            loop = asyncio.get_running_loop()
            await loop.run_in_executor(None, self._create_tables)
            self._initialized = True
            logger.info(f"Reminder storage initialized at {self.db_path}")

    def _create_tables(self) -> None:
        """Create database tables if they don't exist."""
        conn = self._get_connection()
        try:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS reminders (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id TEXT NOT NULL,
                    message TEXT NOT NULL,
                    trigger_time TEXT NOT NULL,
                    is_sent INTEGER DEFAULT 0,
                    created_at TEXT NOT NULL
                )
            """)
            # Index for efficient querying of due reminders
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_trigger_time_sent
                ON reminders(trigger_time, is_sent)
            """)
            # Index for querying user's reminders
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_user_id
                ON reminders(user_id)
            """)
            conn.commit()
        finally:
            conn.close()

    async def add_reminder(self, reminder: Reminder) -> int:
        """Add a new reminder to the database.

        Args:
            reminder: The reminder to add.

        Returns:
            The ID of the newly created reminder.
        """
        await self.initialize()

        loop = asyncio.get_running_loop()
        reminder_id = await loop.run_in_executor(
            None, self._add_reminder_sync, reminder
        )
        logger.info(
            f"Added reminder {reminder_id} for user {reminder.user_id}: "
            f"'{reminder.message[:30]}...' at {reminder.trigger_time}"
        )
        return reminder_id

    def _add_reminder_sync(self, reminder: Reminder) -> int:
        """Synchronous implementation of add_reminder."""
        conn = self._get_connection()
        try:
            cursor = conn.execute(
                """
                INSERT INTO reminders
                (user_id, message, trigger_time, is_sent, created_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    reminder.user_id,
                    reminder.message,
                    reminder.trigger_time,
                    int(reminder.is_sent),
                    reminder.created_at,
                ),
            )
            conn.commit()
            return cursor.lastrowid or 0
        finally:
            conn.close()

    async def get_due_reminders(self) -> list[Reminder]:
        """Get all reminders that are due to be sent.

        Returns:
            List of reminders with trigger_time <= now that haven't been sent.
        """
        await self.initialize()

        now = datetime.now(UTC).isoformat()
        loop = asyncio.get_running_loop()
        reminders = await loop.run_in_executor(None, self._get_due_reminders_sync, now)
        return reminders

    def _get_due_reminders_sync(self, now: str) -> list[Reminder]:
        """Synchronous implementation of get_due_reminders."""
        conn = self._get_connection()
        try:
            cursor = conn.execute(
                """
                SELECT id, user_id, message, trigger_time, is_sent, created_at
                FROM reminders
                WHERE trigger_time <= ? AND is_sent = 0
                ORDER BY trigger_time ASC
                """,
                (now,),
            )
            rows = cursor.fetchall()
            return [self._row_to_reminder(row) for row in rows]
        finally:
            conn.close()

    async def mark_sent(self, reminder_id: int) -> None:
        """Mark a reminder as sent.

        Args:
            reminder_id: The ID of the reminder to mark as sent.
        """
        await self.initialize()

        loop = asyncio.get_running_loop()
        await loop.run_in_executor(None, self._mark_sent_sync, reminder_id)
        logger.info(f"Marked reminder {reminder_id} as sent")

    def _mark_sent_sync(self, reminder_id: int) -> None:
        """Synchronous implementation of mark_sent."""
        conn = self._get_connection()
        try:
            conn.execute(
                "UPDATE reminders SET is_sent = 1 WHERE id = ?",
                (reminder_id,),
            )
            conn.commit()
        finally:
            conn.close()

    async def get_user_reminders(
        self, user_id: str, include_sent: bool = False
    ) -> list[Reminder]:
        """Get all reminders for a specific user.

        Args:
            user_id: The Telegram chat ID of the user.
            include_sent: Whether to include already-sent reminders.

        Returns:
            List of the user's reminders.
        """
        await self.initialize()

        loop = asyncio.get_running_loop()
        reminders = await loop.run_in_executor(
            None, self._get_user_reminders_sync, user_id, include_sent
        )
        return reminders

    def _get_user_reminders_sync(
        self, user_id: str, include_sent: bool
    ) -> list[Reminder]:
        """Synchronous implementation of get_user_reminders."""
        conn = self._get_connection()
        try:
            if include_sent:
                cursor = conn.execute(
                    """
                    SELECT id, user_id, message, trigger_time, is_sent, created_at
                    FROM reminders
                    WHERE user_id = ?
                    ORDER BY trigger_time ASC
                    """,
                    (user_id,),
                )
            else:
                cursor = conn.execute(
                    """
                    SELECT id, user_id, message, trigger_time, is_sent, created_at
                    FROM reminders
                    WHERE user_id = ? AND is_sent = 0
                    ORDER BY trigger_time ASC
                    """,
                    (user_id,),
                )
            rows = cursor.fetchall()
            return [self._row_to_reminder(row) for row in rows]
        finally:
            conn.close()

    async def delete_reminder(self, reminder_id: int, user_id: str) -> bool:
        """Delete a reminder.

        Args:
            reminder_id: The ID of the reminder to delete.
            user_id: The user ID (for authorization check).

        Returns:
            True if deleted, False if not found or not authorized.
        """
        await self.initialize()

        loop = asyncio.get_running_loop()
        deleted = await loop.run_in_executor(
            None, self._delete_reminder_sync, reminder_id, user_id
        )
        if deleted:
            logger.info(f"Deleted reminder {reminder_id}")
        return deleted

    def _delete_reminder_sync(self, reminder_id: int, user_id: str) -> bool:
        """Synchronous implementation of delete_reminder."""
        conn = self._get_connection()
        try:
            cursor = conn.execute(
                "DELETE FROM reminders WHERE id = ? AND user_id = ?",
                (reminder_id, user_id),
            )
            conn.commit()
            return cursor.rowcount > 0
        finally:
            conn.close()

    def _row_to_reminder(self, row: sqlite3.Row) -> Reminder:
        """Convert a database row to a Reminder object."""
        return Reminder(
            id=row["id"],
            user_id=row["user_id"],
            message=row["message"],
            trigger_time=row["trigger_time"],
            is_sent=bool(row["is_sent"]),
            created_at=row["created_at"],
        )


# Global storage instance
_storage: ReminderStorage | None = None


def get_storage() -> ReminderStorage:
    """Get the global reminder storage instance.

    Returns:
        The global ReminderStorage instance.
    """
    global _storage
    if _storage is None:
        _storage = ReminderStorage()
    return _storage
